/* Source-system views retain their own sessions and authorization. No KPI copies. */
(function(){
 if(window.COMPANY_CONNECTED_SYSTEMS)return;window.COMPANY_CONNECTED_SYSTEMS=true;
 const systems={
  audit:{name:'Audit · ออดิทส่วนกลาง',url:'https://work89support.github.io/Audit-Reconciliation-Control/',description:'รอบตรวจ ข้อผิดปกติ การชี้แจง และผลตรวจจากระบบ Audit',pages:[['dashboard','ภาพรวม'],['exceptions','เคสผิดปกติ'],['intake','ความครบของไฟล์'],['matching','ผลจับคู่'],['approvals','รออนุมัติ'],['damage','ความเสียหาย'],['kpi','KPI ต้นทาง'],['reports','รายงาน']],embedded:true},
  domainwatch:{name:'Domainwatch · แอดมินและ IT',url:'https://domain-watch-app-sandy.vercel.app',description:'สถานะโดเมน เคสลิงก์ และผลงานของแอดมิน/IT แยกตามหน้าที่',pages:[['','ภาพรวม'],['incidents','เหตุการณ์'],['kpi','KPI รายคน'],['report','รายงาน'],['case-history','ประวัติเคส'],['links','รายการลิงก์']],embedded:false}
 };
 let selected='audit',page='exceptions';
 const href=(key,route)=>systems[key].url+(key==='audit'?'#/'+route:'/'+route);
 NAV.connectedSystems={t:'ผลจากระบบอื่น',ic:'i-grid'};
 NAVGROUPS.find(g=>g.label==='วัดผล & รายงาน').items.push('connectedSystems');
 for(const roles of [ROLE_ALLOW,SIMPLE_ALLOW])for(const allow of Object.values(roles))if(!allow.includes('connectedSystems'))allow.push('connectedSystems');
 RENDER.connectedSystems=function(){
  if(!ACCESS_PROFILE){main.innerHTML='<p>กรุณาเข้าสู่ Company Hub ก่อนเปิดระบบที่เกี่ยวข้อง</p>';return;}
  const system=systems[selected],url=href(selected,page);
  main.innerHTML=`${crumb('หน้าแรก','ผลจากระบบอื่น')}<div class="page-h"><div><h1>ผลจากระบบอื่น</h1><p>ดูงานและผลลัพธ์จากระบบต้นทาง ตามสิทธิ์บัญชีของแต่ละระบบ</p></div></div>
  <div class="connected-cards">${Object.entries(systems).map(([key,s])=>`<button class="connected-source ${key===selected?'selected':''}" data-system="${key}" aria-pressed="${key===selected}"><strong>${s.name}</strong><span>${s.description}</span><small>${s.embedded?'ดูภายในหน้านี้หรือเปิดเต็มจอ':'เปิดระบบต้นทาง · ใช้บัญชี Domainwatch'}</small></button>`).join('')}</div>
  <section class="card connected-view"><div class="connected-heading"><div><h2>${system.name}</h2><p>ข้อมูลและเวลาอัปเดตแสดงตามต้นทาง · ยังไม่รวมเข้าคะแนน KPI ของ Company Hub</p></div><a class="tbtn primary" id="connected-full" href="${url}" target="_blank" rel="noopener noreferrer">เปิดเต็มจอ / เข้าสู่ระบบ ↗</a></div>
  <nav class="connected-pages" aria-label="หน้าของระบบต้นทาง">${system.pages.map(([route,label])=>system.embedded?`<button class="tbtn ${route===page?'primary':''}" data-source-page="${route}" aria-pressed="${route===page}">${label}</button>`:`<a class="tbtn" href="${href(selected,route)}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`).join('')}</nav>
  ${system.embedded?`<p class="connected-help">หากยังไม่เข้าสู่ Audit ให้ใช้บัญชี Audit ของคุณ หากหน้าว่างให้กดเปิดเต็มจอ</p><iframe id="connected-frame" title="Audit · ${system.pages.find(p=>p[0]===page)?.[1]||'ผลจากระบบต้นทาง'}" src="${url}" referrerpolicy="no-referrer"></iframe>`:`<div class="connected-external"><h3>เปิดผลจริงจาก Domainwatch</h3><p>เลือกภาพรวม เหตุการณ์ KPI รายคน หรือรายงานด้านบน ระบบจะเปิดในแท็บใหม่และใช้สิทธิ์ Domainwatch ของคุณ</p><p>Domainwatch ใช้การเข้าสู่ระบบคนละเว็บไซต์ จึงเปิดผลในระบบต้นทางเพื่อให้เซสชันทำงานได้ครบ</p></div>`}</section>`;
  main.querySelectorAll('[data-system]').forEach(b=>b.onclick=()=>{selected=b.dataset.system;page=selected==='audit'?'exceptions':'';RENDER.connectedSystems();});
  main.querySelectorAll('[data-source-page]').forEach(b=>b.onclick=()=>{page=b.dataset.sourcePage;RENDER.connectedSystems();});
 };
 const dashboard=RENDER.dash;RENDER.dash=function(...args){const r=dashboard(...args);if(!document.getElementById('connected-shortcut')){const box=document.createElement('section');box.id='connected-shortcut';box.className='card connected-shortcut';box.innerHTML='<div><h3>Audit และ Domainwatch</h3><p>เปิดผลตรวจ เคสค้าง และ KPI จากระบบต้นทาง</p></div><button class="tbtn primary">ดูผลจากระบบอื่น →</button>';box.querySelector('button').onclick=()=>go('connectedSystems');main.append(box);}return r;};
 const css=document.createElement('style');css.textContent=`.connected-cards{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:20px 0}.connected-source{display:flex;flex-direction:column;gap:10px;padding:22px;text-align:left;border:1px solid var(--line);border-radius:16px;background:var(--surface);color:var(--ink);font:inherit;cursor:pointer}.connected-source strong{font-size:18px}.connected-source span,.connected-source small{color:var(--muted)}.connected-source.selected{border:2px solid var(--blue-500);padding:21px;background:var(--blue-50)}.connected-heading,.connected-shortcut{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:20px}.connected-heading h2{font-size:19px;margin:0 0 8px}.connected-heading p,.connected-shortcut p,.connected-help{color:var(--muted);font-size:13px}.connected-pages{display:flex;flex-wrap:wrap;gap:8px;padding:0 20px 12px}.connected-help{padding:0 20px}.connected-view iframe{display:block;width:100%;height:78vh;min-height:520px;border:0;border-top:1px solid var(--line);background:white}.connected-external{padding:30px;border-top:1px solid var(--line);line-height:1.8}.connected-shortcut{margin-top:20px}.connected-shortcut h3{margin:0}.connected-view a{text-decoration:none}@media(max-width:650px){.connected-cards{grid-template-columns:1fr}.connected-heading,.connected-shortcut{align-items:stretch;flex-direction:column}.connected-view iframe{min-height:600px}.connected-source{padding:18px}}`;
 document.head.append(css);buildNav();if(VIEW==='dash')RENDER.dash();
})();
