/* Progressive presentation enhancement. Reuses existing nodes and handlers. */
(function(){
 if(window.COMPANY_UX_READY)return;window.COMPANY_UX_READY=true;
 const style=document.createElement('link');style.rel='stylesheet';style.href='ux-system.css?v=20260909-wizard';document.head.append(style);document.body.classList.add('ux-ready');
 const PAGE_HINTS={reports:'เลือกช่วงเวลาและแผนกเพื่อดูผลสรุป แล้วเปิดรายการต้นทาง',monthly:'ตรวจยอดประจำเดือน แล้วบันทึกสรุปและสิ่งที่ต้องการการสนับสนุน',account:'จัดการชื่อ อีเมล และรหัสผ่านของคุณ',teamAccounts:'ตรวจรายชื่อแยกแผนก สร้างบัญชี และดูสถานะการตั้งรหัสผ่าน'};
 function health(){const node=document.getElementById('data-health');if(!node||node.dataset.uxHealth)return;const entries=Object.values(DATA_HEALTH),errors=entries.filter(s=>s.state==='error').length,ready=entries.filter(s=>s.state==='ready').length;const details=document.createElement('details');details.id='data-health';details.className='ux-health'+(errors?' has-error':'');details.dataset.uxHealth='1';details.setAttribute('role','status');details.open=errors>0;const summary=document.createElement('summary');summary.textContent=errors?`ข้อมูล ${errors} แหล่งโหลดไม่สำเร็จ · ดูรายละเอียด`:`สถานะข้อมูล · โหลดแล้ว ${ready}/${entries.length} แหล่ง`;const body=document.createElement('div');while(node.firstChild)body.append(node.firstChild);details.append(summary,body);node.replaceWith(details);}
 function sources(root){root.querySelectorAll('.source-row').forEach(row=>{if(row.closest('.ux-source'))return;const details=document.createElement('details');details.className='ux-source';const summary=document.createElement('summary');summary.textContent='แหล่งข้อมูลและขอบเขตการใช้งาน';row.before(details);details.append(summary,row);});}
 function orderPage(){const heading=main.querySelector(':scope > .page-h'),crumb=main.querySelector(':scope > .crumb'),status=main.querySelector(':scope > #data-health'),nav=main.querySelector(':scope > .ux-section-nav');const priority=[crumb,heading,status,nav];if(VIEW==='dash')priority.push(main.querySelector(':scope > .stats'),main.querySelector(':scope > .department-start'));if(VIEW==='kpi')priority.push(main.querySelector('#kpi-work-report'));let cursor=main.firstElementChild;for(const node of priority.filter(Boolean)){if(node===cursor)cursor=cursor.nextElementSibling;else main.insertBefore(node,cursor);}}
 function compactFilters(){if(!['board','timeline'].includes(VIEW))return;for(const bar of main.querySelectorAll('.filterbar')){if(bar.dataset.uxFilters)continue;const fields=[...bar.children].filter(n=>n.classList.contains('fsel'));if(fields.length<6)continue;bar.dataset.uxFilters='1';const details=document.createElement('details');details.className='ux-advanced-filters';const summary=document.createElement('summary');summary.textContent='ตัวกรองเพิ่มเติม · ผู้รับผิดชอบ วันที่ และการจัดเรียง';const body=document.createElement('div');body.className='ux-advanced-grid';details.append(summary,body);fields.slice(3).forEach(n=>body.append(n));details.open=!!(F.assignee||F.dateFrom||F.dateTo||F.period);bar.append(details);}}
 function reportDepartments(){if(!['reports','monthly'].includes(VIEW))return;for(const section of main.querySelectorAll('.card.pad')){if(section.dataset.uxReport||section.querySelector('h3')?.textContent!=='รายการแยกแผนก')continue;section.dataset.uxReport='1';const grid=document.createElement('div');grid.className='ux-report-depts';for(const button of [...section.querySelectorAll(':scope > button')]){const parts=button.textContent.match(/^(.*?) · งาน (\d+) · กิจกรรม (\d+) · ปัญหา (\d+)$/);if(!parts)continue;button.classList.add('ux-report-dept');button.innerHTML='<strong>'+esc(parts[1])+'</strong><span class="ux-report-counts">'+['งาน','กิจกรรม','ปัญหา'].map((label,i)=>'<span><b>'+parts[i+2]+'</b>'+label+'</span>').join('')+'</span>';grid.append(button);}section.append(grid);}}
 function toolbar(){document.querySelectorAll('.topbar .tbtn').forEach(button=>{if(button.dataset.uxLabel)return;button.dataset.uxLabel='1';if(!button.getAttribute('aria-label'))button.setAttribute('aria-label',button.textContent.trim());for(const node of [...button.childNodes])if(node.nodeType===3&&node.textContent.trim()){const span=document.createElement('span');span.className='ux-button-label';node.before(span);span.append(node);}});}
 function quality(){if(VIEW!=='dash')return;const card=[...main.querySelectorAll(':scope > .card')].find(n=>n.querySelector('h3')?.textContent==='ข้อมูลที่ยังใช้ประเมินไม่ได้');if(!card||card.dataset.uxQuality)return;card.dataset.uxQuality='1';const title=card.querySelector('h3'),details=document.createElement('details');details.className='ux-quality';details.open=dashboardAllWork().some(t=>!dashboardDueAt(t));const summary=document.createElement('summary');summary.textContent='ความครบถ้วนของข้อมูล · ตรวจรายละเอียด';details.append(summary);title.remove();while(card.firstChild)details.append(card.firstChild);card.append(details);}
 function approval(){const input=document.getElementById('kpi-result-month');if(!input)return;const section=input.closest('section');if(!section||section.dataset.uxApproval)return;section.dataset.uxApproval='1';const row=document.createElement('div');row.className='ux-approval-controls';const month=input.closest('label'),select=document.getElementById('kpi-result-definition'),button=document.getElementById('kpi-result-open');if(month)row.append(month);if(select){const label=document.createElement('label');label.textContent='ตัวชี้วัดที่ต้องการบันทึก';label.append(select);row.append(label);}if(button)row.append(button);section.append(row);}
 function headers(){const heading=main.querySelector(':scope > h1');if(heading){const wrapper=document.createElement('div');wrapper.className='page-h';const title=document.createElement('div');heading.before(wrapper);title.append(heading);if(PAGE_HINTS[VIEW]){const p=document.createElement('p');p.textContent=PAGE_HINTS[VIEW];title.append(p);}wrapper.append(title);}}
 function draft(){const form=document.getElementById('report-draft-form');if(!form||form.dataset.uxDraft)return;form.dataset.uxDraft='1';const groups=[['ผลการดำเนินงาน',['highlight','resolution','post']],['ประเด็นที่ต้องตัดสินใจ',['urgent','decision']],['การสนับสนุนและบันทึกเพิ่มเติม',['supportOther','supportExec','note']]];for(const [title,keys]of groups){const fieldset=document.createElement('fieldset');fieldset.className='ux-draft-group';const legend=document.createElement('legend');legend.textContent=title;fieldset.append(legend);for(const key of keys){const field=document.getElementById('report-'+key);if(field?.parentElement.tagName==='LABEL')fieldset.append(field.parentElement);}if(fieldset.children.length>1)form.insertBefore(fieldset,document.getElementById('report-error'));}}
 function criteria(){if(VIEW!=='kpi')return;for(const [code,defs]of Object.entries(KPI_CATALOG)){const section=[...main.querySelectorAll(':scope > section.card')].find(s=>!s.dataset.uxCriteria&&s.id!=='kpi-work-report'&&s.querySelector(':scope > h3')?.textContent===deptName(code));if(!section)continue;section.dataset.uxCriteria='1';const h=section.querySelector('h3');section.replaceChildren(h);const grid=document.createElement('div');grid.className='ux-kpi-grid';grid.innerHTML=defs.map(d=>`<article class="ux-kpi-criterion"><h4>${esc(d.n)}</h4><div class="ux-kpi-metrics"><div><span>เป้าหมาย</span><b>${esc(d.tg)}</b></div><div><span>น้ำหนัก</span><b>${Math.round(d.w*100)}%</b></div><div><span>ผลจริง</span><b>${d.ac==null?'รอบันทึก':esc(acDisp(d))}</b></div></div><p>${esc(d.period||'ยังไม่มีผลจริง')} · ${esc({draft:'ร่าง',review:'รอตรวจ',approved:'รับรองแล้ว',locked:'ล็อกรอบ'}[d.status]||d.status||'รอบันทึก')}</p><details><summary>สูตรและหลักฐานที่ต้องใช้</summary>${kpiDefinitionDetails({formula:d.formula,prototype_payload:d.metadata})}</details></article>`).join('');section.append(grid);}}
 function navigation(){if(!['kpi','sop','completeness','monthly'].includes(VIEW)||main.querySelector('.ux-section-nav'))return;const sections=[...main.querySelectorAll(':scope > section.card > h3,:scope > .sect-title,:scope > h3')].filter(h=>h.textContent.trim());if(sections.length<3)return;const nav=document.createElement('nav');nav.className='ux-section-nav';nav.setAttribute('aria-label','ส่วนต่าง ๆ ของหน้านี้');sections.slice(0,12).forEach(h=>{const button=document.createElement('button');button.type='button';button.textContent=h.textContent.trim();button.onclick=()=>h.scrollIntoView({behavior:'smooth',block:'start'});nav.append(button);});const header=main.querySelector('.page-h');if(header)header.after(nav);}
 function accessible(root){root.querySelectorAll('td[colspan]').forEach(td=>{if(!td.querySelector('input,button,a')&&/ไม่พบ|ไม่มี|กำลังโหลด/.test(td.textContent))td.classList.add('ux-empty-cell');});root.querySelectorAll('.tile[onclick],.orgteam[onclick],.ann[onclick],.stat.click[onclick]').forEach(el=>{if(el.dataset.uxKeyboard)return;el.dataset.uxKeyboard='1';el.tabIndex=0;el.setAttribute('role','button');el.addEventListener('keydown',e=>{if(e.target===el&&(e.key==='Enter'||e.key===' ')){e.preventDefault();el.click();}});});root.querySelectorAll('input:not([type=hidden]),select,textarea').forEach(el=>{if(el.closest('label')||el.getAttribute('aria-label')||el.id&&root.querySelector(`label[for="${CSS.escape(el.id)}"]`))return;const label=el.parentElement.querySelector(':scope > label');if(label){if(!el.id)el.id='ux-field-'+(++fieldNumber);label.htmlFor=el.id;}else if(el.placeholder)el.setAttribute('aria-label',el.placeholder);});}
 let fieldNumber=0,busy=false;
 function enhance(){if(busy||!main)return;busy=true;try{main.dataset.uxView=VIEW;headers();health();sources(main);draft();criteria();approval();compactFilters();reportDepartments();quality();toolbar();navigation();orderPage();accessible(main);}finally{busy=false;}}
 function enhanceModal(){const root=document.getElementById('modal');if(!root)return;accessible(root);const headings=[...root.querySelectorAll('form h4')];if(headings.length>1&&!root.querySelector('.ux-form-guide,.entry-wizard')){const guide=document.createElement('nav');guide.className='ux-form-guide';guide.setAttribute('aria-label','ส่วนของแบบฟอร์ม');headings.forEach((h,i)=>{const button=document.createElement('button');button.type='button';button.innerHTML=`<b>${i+1}</b> ${esc(h.textContent.replace(/^\d+[.·\s-]*/,''))}`;button.onclick=()=>h.scrollIntoView({behavior:'smooth',block:'start'});guide.append(button);});root.querySelector('.modal-h')?.after(guide);}}
 // Focused workspace: backlog is separate from period-based activity totals.
 const workspace={scope:'mine',period:'today',tab:'open',limit:12};
 const completion={kind:'activity',origin:'all',limit:30};
 function scopedWork(){if(AUTH_DB_ROLE==='staff')workspace.scope='mine';return boardAllWork().filter(w=>workspace.scope!=='mine'||teamWorkPeople(w).some(p=>p.key==='user:'+ACCESS_PROFILE?.id));}
 function knownCount(keys,n){return keys.every(k=>DATA_HEALTH[k]?.state==='ready')?nf(n):'…';}
 function workRow(w,i){return `<button class="ux-work-row" data-work-index="${i}"><span class="ux-work-icon" aria-hidden="true">${({task:'✓',graphic:'▧',activity:'≡',issue:'!'})[w._source]||'•'}</span><span class="ux-work-copy"><strong>${esc(w.title)}</strong><small>${esc(deptName(w.dept))} · ${esc(teamWorkPeople(w).map(p=>p.name).join(', '))}</small></span><span class="ux-work-end"><span class="ux-status ${['done','block','review','doing'].includes(w.status)?w.status:'todo'}">${esc(STATUS[w.status]?.t||w.status)}</span><small>${esc(teamWorkMeta(w))}</small></span></button>`;}
 RENDER.dash=function(){
  const rows=scopedWork(),work=rows.filter(w=>['task','graphic'].includes(w._source)),open=work.filter(w=>w.status!=='done'),late=open.filter(dashboardIsOverdue),noDue=open.filter(w=>!dashboardDueAt(w)),issues=rows.filter(w=>w._source==='issue'&&w.status!=='done'),range=integrityRange(workspace.period),activities=rows.filter(w=>w._source==='activity'&&integrityInRange(w.sourceRow.activity_date,range)),periodIssues=rows.filter(w=>w._source==='issue'&&integrityInRange(w.sourceRow.date,range));
  const choices={open:{label:'งานที่ยังไม่เสร็จ',rows:open},late:{label:'เลยกำหนดส่ง',rows:late},noDue:{label:'ยังไม่มีวันส่ง',rows:noDue},issues:{label:'ปัญหาที่ยังไม่ปิด',rows:issues}};
  const selected=choices[workspace.tab],list=selected.rows.slice().sort((a,b)=>(dashboardDueAt(a)?.getTime()||Infinity)-(dashboardDueAt(b)?.getTime()||Infinity)||teamWorkDay(b).localeCompare(teamWorkDay(a)));
  const keys=['tasks',...(canViewDept('GRAPHIC')?['graphic']:[])];
  main.innerHTML=`${crumb('หน้าแรก','พื้นที่ทำงาน')}<div class="page-h"><div><span class="ux-eyebrow">COMPANY HUB · ${esc(deptName(currentDept()))}</span><h1>วันนี้ มีอะไรต้องทำบ้าง</h1><p>งานที่รับผิดชอบ กิจกรรม และปัญหาในที่เดียว</p></div><button class="tbtn primary" id="ux-create">+ ${currentDept()==='GRAPHIC'?'รับบรีฟใหม่':currentDept()==='ADMIN'?'แจ้งปัญหา':'บันทึกกิจกรรม'}</button></div>
  <div class="ux-workspace-bar"><div class="ux-segments" aria-label="ขอบเขตงาน">${Object.entries({mine:'ของฉัน',...(AUTH_DB_ROLE!=='staff'?{visible:'ทุกแผนกที่ฉันมีสิทธิ์'}:{})}).map(([key,label])=>`<button data-scope="${key}" aria-pressed="${workspace.scope===key}">${label}</button>`).join('')}</div><span class="muted">งานค้างรวมทุกช่วงเวลา</span></div>
  <div class="ux-summary-grid">${[['open','งานที่ยังไม่เสร็จ',open.length,'งานมอบหมายและกราฟิก',keys],['late','เลยกำหนดส่ง',late.length,'นับเฉพาะงานที่มีวันส่ง',keys],['noDue','ยังไม่มีวันส่ง',noDue.length,'ยังประเมินความตรงเวลาไม่ได้',keys],['issues','ปัญหาที่ยังไม่ปิด',issues.length,'แยกจากสถานะติดปัญหาของงาน',['issues']]].map(([key,label,n,hint,sources])=>`<button class="ux-summary ${workspace.tab===key?'selected':''}" data-work-tab="${key}" aria-pressed="${workspace.tab===key}"><span>${label}</span><strong>${knownCount(sources,n)}</strong><small>${hint}</small></button>`).join('')}</div>
  <div class="ux-workspace-grid"><section class="card ux-work-panel"><div class="card-h"><h3>${selected.label}</h3><span class="muted">${list.length} รายการในข้อมูลที่โหลด</span></div><div>${list.slice(0,workspace.limit).map(workRow).join('')||'<div class="ux-empty">ไม่มีรายการในขอบเขตนี้<br><small>หากสถานะข้อมูลยังโหลดอยู่ ยอดจะอัปเดตเมื่อโหลดครบ</small></div>'}</div>${list.length>workspace.limit?'<button class="tbtn ux-show-more" id="ux-work-more">แสดงเพิ่มอีก 12 รายการ</button>':''}</section>
  <aside class="ux-workspace-aside"><section class="card pad"><h3>กิจกรรมในช่วงเวลา</h3><div class="ux-segments">${Object.entries({today:'วันนี้',week:'สัปดาห์นี้',month:'เดือนนี้'}).map(([key,label])=>`<button data-period="${key}" aria-pressed="${workspace.period===key}">${label}</button>`).join('')}</div><p class="muted">${esc(range.from)} — ${esc(range.to)}</p><div class="ux-period-count"><span>บันทึกกิจกรรม</span><b>${knownCount(['activity'],activities.length)}</b></div><div class="ux-period-count"><span>ปัญหาที่เกิดในช่วงนี้</span><b>${knownCount(['issues'],periodIssues.length)}</b></div><small class="muted">แยกตามวันทำงานและวันเกิดเหตุ ไม่รวมเป็นคะแนน KPI</small></section><section class="card pad ux-shortcuts"><h3>ทำต่อได้ทันที</h3>${[['teamBoard','บอร์ดทีม / รายคน','ติดตามความคืบหน้า'],['completeness','ข้อมูลที่ต้องเติม','เจ้าของ เวลา และผลลัพธ์'],['kpi','KPI และหลักฐาน','ตรวจงานที่แท็กและผลรับรอง'],['ann','ประกาศบริษัท','อ่าน รับทราบ และถามตอบ']].map(([view,title,hint])=>`<button data-workspace-go="${view}"><span><b>${title}</b><small>${hint}</small></span><span aria-hidden="true">↗</span></button>`).join('')}</section></aside></div>`;
  document.getElementById('ux-create').onclick=()=>currentDept()==='GRAPHIC'?openGraphicBrief():currentDept()==='ADMIN'?openNewIssue():openActivityEntry();
  main.querySelectorAll('[data-scope]').forEach(b=>b.onclick=()=>{workspace.scope=b.dataset.scope;RENDER.dash();});
  main.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{workspace.period=b.dataset.period;RENDER.dash();});
  main.querySelectorAll('[data-work-tab]').forEach(b=>b.onclick=()=>{workspace.tab=b.dataset.workTab;workspace.limit=12;RENDER.dash();});
  main.querySelectorAll('[data-work-index]').forEach(b=>b.onclick=()=>{const w=list[Number(b.dataset.workIndex)];openTeamWork(w._source,w.sourceId||w.id);});
  main.querySelectorAll('[data-workspace-go]').forEach(b=>b.onclick=()=>{if(b.dataset.workspaceGo==='completeness')ENTRY_SCOPE='mine';go(b.dataset.workspaceGo);});
  const more=document.getElementById('ux-work-more');if(more)more.onclick=()=>{workspace.limit+=12;RENDER.dash();};
  integrityRenderHealth();
 };
 function imported(kind,row){return kind==='activity'?!!row.source_document_id:kind==='issue'?!!row.sourceSheet:!!row.trello_card_id;}
 RENDER.completeness=function(){
  if(AUTH_DB_ROLE==='staff')ENTRY_SCOPE='mine';
  const q=entryQueue(),graphics=GRAPHIC_JOBS.filter(j=>canViewDept('GRAPHIC')&&j.status!=='done'&&(!j.due_at||!j.assignee_id)&&(canManageGraphic()||j.assignee_id===ACCESS_PROFILE?.id)&&(ENTRY_SCOPE!=='mine'||j.assignee_id===ACCESS_PROFILE?.id));
  const groups={activity:q.activities,issue:q.issues,graphic:graphics};
  const filtered=Object.fromEntries(Object.entries(groups).map(([kind,rows])=>[kind,rows.filter(r=>completion.origin==='all'||(completion.origin==='imported'?imported(kind,r):!imported(kind,r))).sort((a,b)=>String(b.activity_date||b.date||b.created_at||'').localeCompare(String(a.activity_date||a.date||a.created_at||'')))]));
  const kind=completion.kind,rows=filtered[kind];
  main.innerHTML=`${crumb('หน้าแรก','ข้อมูลที่ต้องเติม')}<div class="page-h"><div><h1>เติมข้อมูลให้พร้อมส่งงาน</h1><p>เปิดรายการเพื่อเติมช่องที่ขาด · เรียงวันที่ล่าสุดก่อน · ข้อมูลที่ครบแล้วจะออกจากคิว</p></div></div><div class="ux-workspace-bar"><div class="ux-segments">${Object.entries({mine:'ของฉัน',...(AUTH_DB_ROLE!=='staff'?{team:'ทีมที่ฉันจัดการ'}:{})}).map(([k,v])=>`<button data-entry-scope="${k}" aria-pressed="${ENTRY_SCOPE===k}">${v}</button>`).join('')}</div><label>แหล่งที่มา <select id="ux-entry-origin" class="fin">${Object.entries({all:'ทั้งหมด',native:'กรอกในระบบ',imported:'ประวัตินำเข้า'}).map(([k,v])=>`<option value="${k}" ${completion.origin===k?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="ux-segments ux-queue-tabs">${Object.entries({activity:'กิจกรรม',issue:'ปัญหาหน้างาน',graphic:'กราฟิก'}).map(([k,v])=>`<button data-entry-kind="${k}" aria-pressed="${kind===k}">${v} <b>${filtered[k].length}</b></button>`).join('')}</div><p class="muted">${ENTRY_SCOPE==='mine'?'เฉพาะรายการของคุณ':'เฉพาะรายการที่คุณมีสิทธิ์จัดการ'}${q.activities.some(r=>!r.employee_id)&&ENTRY_SCOPE==='team'?' · งานที่ยังไม่เชื่อมบัญชีต้องให้หัวหน้าเลือกเจ้าของก่อน':''}</p><div class="ux-queue-list">${rows.slice(0,completion.limit).map((r,i)=>{const missing=kind==='activity'?entryMissing(r):kind==='issue'?issueEntryMissing(r):[...(!r.due_at?['วันส่ง']:[]),...(!r.assignee_id?['บัญชีเจ้าของ']:[])];return `<article class="card ux-queue-item"><div><small>${esc(kind==='activity'?r.employee_name||'ยังไม่ระบุเจ้าของ':kind==='issue'?r.owner||'ยังไม่ระบุทีม':r.assignee_name||'ยังไม่มอบหมาย')} · ${esc(r.activity_date||r.date||String(r.created_at||'').slice(0,10))} · ${imported(kind,r)?'นำเข้า':'กรอกในระบบ'}</small><h3>${esc(r.activity||r.problem||r.title)}</h3><div class="ux-missing-fields">${missing.map(m=>`<span>${esc(m)}</span>`).join('')}</div></div><button class="tbtn" data-entry-index="${i}">เติมข้อมูล ↗</button>${kind==='issue'?`<button class="tbtn" data-issue-follow="${i}">ติดตาม / ยืนยันผล</button>`:''}</article>`;}).join('')||'<div class="card ux-empty">ไม่มีข้อมูลที่ต้องเติมในตัวกรองนี้</div>'}</div>${rows.length>completion.limit?'<button class="tbtn ux-show-more" id="ux-entry-more">แสดงเพิ่มอีก 30 รายการ</button>':''}`;
  main.querySelectorAll('[data-entry-scope]').forEach(b=>b.onclick=()=>{ENTRY_SCOPE=b.dataset.entryScope;completion.limit=30;RENDER.completeness();});
  main.querySelectorAll('[data-entry-kind]').forEach(b=>b.onclick=()=>{completion.kind=b.dataset.entryKind;completion.limit=30;RENDER.completeness();});
  document.getElementById('ux-entry-origin').onchange=e=>{completion.origin=e.target.value;completion.limit=30;RENDER.completeness();};
  main.querySelectorAll('[data-entry-index]').forEach(b=>b.onclick=()=>{const r=rows[Number(b.dataset.entryIndex)];if(kind==='activity')openActivityEntry(r.id);else if(kind==='issue')openIssueEntry(r.id);else openGraphicJob(r.id);});
  main.querySelectorAll('[data-issue-follow]').forEach(b=>b.onclick=()=>openProblem(rows[Number(b.dataset.issueFollow)].id));
  const more=document.getElementById('ux-entry-more');if(more)more.onclick=()=>{completion.limit+=30;RENDER.completeness();};
  integrityRenderHealth();
 };

 for(const view of Object.keys(RENDER)){const original=RENDER[view];RENDER[view]=function(...args){const active=document.activeElement,keep=VIEW===view&&main.contains(active)&&active.tagName==='INPUT'&&['search','text'].includes(active.type)&&!!active.closest('.filterbar,.issue-work-filters,.activity-filters');const focus=keep?{id:active.id,placeholder:active.placeholder,value:active.value,start:active.selectionStart,end:active.selectionEnd}:null;const finish=()=>{enhance();if(focus&&VIEW===view){const input=focus.id?document.getElementById(focus.id):[...main.querySelectorAll('input')].find(n=>n.placeholder===focus.placeholder&&n.value===focus.value);if(input&&input.value===focus.value){input.focus({preventScroll:true});try{input.setSelectionRange(focus.start,focus.end);}catch{}}}};const result=original(...args);finish();if(result?.then)return result.then(value=>{if(VIEW===view)finish();return value;});return result;};}
 // A loader can finish after the initial dashboard render. Refresh the counts once
 // per health transition so a ready source never leaves a loading placeholder behind.
 const workspaceHealth=integrityRenderHealth;let healthSignature='',healthQueued=false;
 integrityRenderHealth=function(...args){const result=workspaceHealth(...args);const signature=JSON.stringify(Object.entries(DATA_HEALTH).map(([k,s])=>[k,s.state,s.at]));if(VIEW==='dash'&&signature!==healthSignature){healthSignature=signature;if(!healthQueued){healthQueued=true;queueMicrotask(()=>{healthQueued=false;if(VIEW==='dash')RENDER.dash();});}}return result;};
 let modalOrigin=null;
 function arrangeModal(){
  const root=document.getElementById('modal'),header=root.querySelector('.modal-h');
  root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.tabIndex=-1;
  const title=header?.querySelector('h3');if(title){title.id='ux-dialog-title';root.setAttribute('aria-labelledby',title.id);}else{root.removeAttribute('aria-labelledby');root.setAttribute('aria-label','รายละเอียดและอัปเดต');}
  const close=header?.querySelector('.x');if(close)close.setAttribute('aria-label',(close.getAttribute('onclick')||'').includes('closeModal')?'ปิดหน้าต่าง':'กลับไปรายละเอียด');
  // Keep the original form and controls: feature handlers retain their values and submit target.
  root.querySelectorAll('form').forEach(form=>{
   if(form.querySelector('.ux-modal-actions'))return;
   const last=form.lastElementChild;
   if(last?.matches('button.tbtn.primary,button[type=submit]')){
    const footer=document.createElement('div');footer.className='ux-modal-actions';last.before(footer);footer.append(last);
    const cancel=document.createElement('button');cancel.type='button';cancel.className='tbtn ux-modal-cancel';cancel.textContent='ยกเลิก';cancel.onclick=()=>close?close.click():closeModal();footer.append(cancel);
   }
  });
  root.scrollTop=0;root.querySelectorAll(':scope > .pad').forEach(n=>n.scrollTop=0);
  document.body.classList.remove('nav-open');document.body.classList.add('ux-modal-open');
  root.focus({preventScroll:true});
 }
 const originalModal=showModal;showModal=function(...args){if(!overlay.classList.contains('show'))modalOrigin=document.activeElement;const result=originalModal(...args);enhanceModal();arrangeModal();return result;};
 const originalCloseModal=closeModal;closeModal=function(...args){const result=originalCloseModal(...args);document.body.classList.remove('ux-modal-open');if(modalOrigin?.isConnected)modalOrigin.focus({preventScroll:true});modalOrigin=null;return result;};
 document.getElementById('overlay').onclick=e=>{if(e.target===e.currentTarget&&!modal.querySelector('input,textarea,select'))closeModal();};
 document.getElementById('overlay').addEventListener('keydown',e=>{
  if(e.key==='Escape'){e.preventDefault();e.stopPropagation();const close=modal.querySelector('.modal-h .x');if(close)close.click();else closeModal();return;}
  if(e.key!=='Tab')return;
  const items=[...modal.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex="0"]')].filter(n=>!n.hidden&&n.getClientRects().length);
  const first=items[0],last=items[items.length-1];
  if(!first){e.preventDefault();modal.focus();return;}
  if(e.shiftKey&&(document.activeElement===first||document.activeElement===modal)){e.preventDefault();last.focus();}
  else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===modal)){e.preventDefault();first.focus();}
 });
 let queued=false;const observer=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance();});});observer.observe(main,{childList:true,subtree:true});
 const wizardScript=document.createElement('script');wizardScript.src='entry-wizard.js?v=20260909-1';document.head.append(wizardScript);
 const connectedScript=document.createElement('script');connectedScript.src='connected-systems.js?v=20260909-results-complete';document.head.append(connectedScript);
 window.companyUxEnhance=enhance;window.companyUxEnhanceModal=enhanceModal;enhance();
})();
