/* Progressive presentation enhancement. Reuses existing nodes and handlers. */
(function(){
 if(window.COMPANY_UX_READY)return;window.COMPANY_UX_READY=true;
 const style=document.createElement('link');style.rel='stylesheet';style.href='ux-system.css?v=20260905-1';document.head.append(style);document.body.classList.add('ux-ready');
 const PAGE_HINTS={reports:'เลือกช่วงเวลาและแผนกเพื่อดูผลสรุป แล้วเปิดรายการต้นทาง',monthly:'ตรวจยอดประจำเดือน แล้วบันทึกสรุปและสิ่งที่ต้องการการสนับสนุน',account:'จัดการชื่อ อีเมล และรหัสผ่านของคุณ',teamAccounts:'ตรวจรายชื่อแยกแผนก สร้างบัญชี และดูสถานะการตั้งรหัสผ่าน'};
 function health(){const node=document.getElementById('data-health');if(!node||node.dataset.uxHealth)return;const entries=Object.values(DATA_HEALTH),errors=entries.filter(s=>s.state==='error').length,ready=entries.filter(s=>s.state==='ready').length;const details=document.createElement('details');details.id='data-health';details.className='ux-health'+(errors?' has-error':'');details.dataset.uxHealth='1';details.setAttribute('role','status');details.open=errors>0;const summary=document.createElement('summary');summary.textContent=errors?`ข้อมูล ${errors} แหล่งโหลดไม่สำเร็จ · ดูรายละเอียด`:`สถานะข้อมูล · อัปเดตแล้ว ${ready}/${entries.length} แหล่ง`;const body=document.createElement('div');while(node.firstChild)body.append(node.firstChild);details.append(summary,body);node.replaceWith(details);}
 function sources(root){root.querySelectorAll('.source-row').forEach(row=>{if(row.closest('.ux-source'))return;const details=document.createElement('details');details.className='ux-source';const summary=document.createElement('summary');summary.textContent='แหล่งข้อมูลและขอบเขตการใช้งาน';row.before(details);details.append(summary,row);});}
 function orderPage(){const heading=main.querySelector(':scope > .page-h'),crumb=main.querySelector(':scope > .crumb'),status=main.querySelector(':scope > #data-health'),nav=main.querySelector(':scope > .ux-section-nav');const priority=[crumb,heading,status,nav];if(VIEW==='dash')priority.push(main.querySelector(':scope > .stats'),main.querySelector(':scope > .department-start'));if(VIEW==='kpi')priority.push(main.querySelector('#kpi-work-report'));let cursor=main.firstElementChild;for(const node of priority.filter(Boolean)){if(node===cursor)cursor=cursor.nextElementSibling;else main.insertBefore(node,cursor);}}
 function compactFilters(){if(!['board','timeline'].includes(VIEW))return;for(const bar of main.querySelectorAll('.filterbar')){if(bar.dataset.uxFilters)continue;const fields=[...bar.children].filter(n=>n.classList.contains('fsel'));if(fields.length<6)continue;bar.dataset.uxFilters='1';const details=document.createElement('details');details.className='ux-advanced-filters';const summary=document.createElement('summary');summary.textContent='ตัวกรองเพิ่มเติม · ผู้รับผิดชอบ วันที่ และการจัดเรียง';const body=document.createElement('div');body.className='ux-advanced-grid';details.append(summary,body);fields.slice(3).forEach(n=>body.append(n));details.open=!!(F.assignee||F.dateFrom||F.dateTo||F.period);bar.append(details);}}
 function reportDepartments(){if(!['reports','monthly'].includes(VIEW))return;for(const section of main.querySelectorAll('.card.pad')){if(section.dataset.uxReport||section.querySelector('h3')?.textContent!=='รายการแยกแผนก')continue;section.dataset.uxReport='1';const grid=document.createElement('div');grid.className='ux-report-depts';for(const button of [...section.querySelectorAll(':scope > button')]){const parts=button.textContent.match(/^(.*?) · งาน (\d+) · กิจกรรม (\d+) · ปัญหา (\d+)$/);if(!parts)continue;button.classList.add('ux-report-dept');button.innerHTML='<strong>'+esc(parts[1])+'</strong><span class="ux-report-counts">'+['งาน','กิจกรรม','ปัญหา'].map((label,i)=>'<span><b>'+parts[i+2]+'</b>'+label+'</span>').join('')+'</span>';grid.append(button);}section.append(grid);}}
 function toolbar(){document.querySelectorAll('.topbar .tbtn').forEach(button=>{if(button.dataset.uxLabel)return;button.dataset.uxLabel='1';if(!button.getAttribute('aria-label'))button.setAttribute('aria-label',button.textContent.trim());for(const node of [...button.childNodes])if(node.nodeType===3&&node.textContent.trim()){const span=document.createElement('span');span.className='ux-button-label';node.before(span);span.append(node);}});}
 function quality(){if(VIEW!=='dash')return;const card=[...main.querySelectorAll(':scope > .card')].find(n=>n.querySelector('h3')?.textContent==='ข้อมูลที่ยังใช้ประเมินไม่ได้');if(!card||card.dataset.uxQuality)return;card.dataset.uxQuality='1';const title=card.querySelector('h3'),details=document.createElement('details');details.className='ux-quality';details.open=dashboardAllWork().some(t=>!dashboardDueAt(t));const summary=document.createElement('summary');summary.textContent='ความครบถ้วนของข้อมูล · ตรวจรายละเอียด';details.append(summary);title.remove();while(card.firstChild)details.append(card.firstChild);card.append(details);}
 function approval(){const input=document.getElementById('kpi-result-month');if(!input)return;const section=input.closest('section');if(!section||section.dataset.uxApproval)return;section.dataset.uxApproval='1';const row=document.createElement('div');row.className='ux-approval-controls';const month=input.closest('label'),select=document.getElementById('kpi-result-definition'),button=document.getElementById('kpi-result-open');if(month)row.append(month);if(select){const label=document.createElement('label');label.textContent='ตัวชี้วัดที่ต้องการบันทึก';label.append(select);row.append(label);}if(button)row.append(button);section.append(row);}
 function headers(){const heading=main.querySelector(':scope > h1');if(heading){const wrapper=document.createElement('div');wrapper.className='page-h';const title=document.createElement('div');heading.before(wrapper);title.append(heading);if(PAGE_HINTS[VIEW]){const p=document.createElement('p');p.textContent=PAGE_HINTS[VIEW];title.append(p);}wrapper.append(title);}}
 function draft(){const form=document.getElementById('report-draft-form');if(!form||form.dataset.uxDraft)return;form.dataset.uxDraft='1';const groups=[['ผลการดำเนินงาน',['highlight','resolution','post']],['ประเด็นที่ต้องตัดสินใจ',['urgent','decision']],['การสนับสนุนและบันทึกเพิ่มเติม',['supportOther','supportExec','note']]];for(const [title,keys]of groups){const fieldset=document.createElement('fieldset');fieldset.className='ux-draft-group';const legend=document.createElement('legend');legend.textContent=title;fieldset.append(legend);for(const key of keys){const field=document.getElementById('report-'+key);if(field?.parentElement.tagName==='LABEL')fieldset.append(field.parentElement);}if(fieldset.children.length>1)form.insertBefore(fieldset,document.getElementById('report-error'));}}
 function criteria(){if(VIEW!=='kpi')return;for(const [code,defs]of Object.entries(KPI_CATALOG)){const section=[...main.querySelectorAll(':scope > section.card')].find(s=>!s.dataset.uxCriteria&&s.id!=='kpi-work-report'&&s.querySelector(':scope > h3')?.textContent===deptName(code));if(!section)continue;section.dataset.uxCriteria='1';const h=section.querySelector('h3');section.replaceChildren(h);const grid=document.createElement('div');grid.className='ux-kpi-grid';grid.innerHTML=defs.map(d=>`<article class="ux-kpi-criterion"><h4>${esc(d.n)}</h4><div class="ux-kpi-metrics"><div><span>เป้าหมาย</span><b>${esc(d.tg)}</b></div><div><span>น้ำหนัก</span><b>${Math.round(d.w*100)}%</b></div><div><span>ผลจริง</span><b>${d.ac==null?'รอบันทึก':esc(acDisp(d))}</b></div></div><p>${esc(d.period||'ยังไม่มีผลจริง')} · ${esc({draft:'ร่าง',review:'รอตรวจ',approved:'รับรองแล้ว',locked:'ล็อกรอบ'}[d.status]||d.status||'รอบันทึก')}</p><details><summary>สูตรและหลักฐานที่ต้องใช้</summary>${kpiDefinitionDetails({formula:d.formula,prototype_payload:d.metadata})}</details></article>`).join('');section.append(grid);}}
 function navigation(){if(!['kpi','sop','completeness','monthly'].includes(VIEW)||main.querySelector('.ux-section-nav'))return;const sections=[...main.querySelectorAll(':scope > section.card > h3,:scope > .sect-title,:scope > h3')].filter(h=>h.textContent.trim());if(sections.length<3)return;const nav=document.createElement('nav');nav.className='ux-section-nav';nav.setAttribute('aria-label','ส่วนต่าง ๆ ของหน้านี้');sections.slice(0,12).forEach(h=>{const button=document.createElement('button');button.type='button';button.textContent=h.textContent.trim();button.onclick=()=>h.scrollIntoView({behavior:'smooth',block:'start'});nav.append(button);});const header=main.querySelector('.page-h');if(header)header.after(nav);}
 function accessible(root){root.querySelectorAll('td[colspan]').forEach(td=>{if(!td.querySelector('input,button,a')&&/ไม่พบ|ไม่มี|กำลังโหลด/.test(td.textContent))td.classList.add('ux-empty-cell');});root.querySelectorAll('.tile[onclick],.orgteam[onclick],.ann[onclick],.stat.click[onclick]').forEach(el=>{if(el.dataset.uxKeyboard)return;el.dataset.uxKeyboard='1';el.tabIndex=0;el.setAttribute('role','button');el.addEventListener('keydown',e=>{if(e.target===el&&(e.key==='Enter'||e.key===' ')){e.preventDefault();el.click();}});});root.querySelectorAll('input:not([type=hidden]),select,textarea').forEach(el=>{if(el.closest('label')||el.getAttribute('aria-label')||el.id&&root.querySelector(`label[for="${CSS.escape(el.id)}"]`))return;const label=el.parentElement.querySelector(':scope > label');if(label){if(!el.id)el.id='ux-field-'+(++fieldNumber);label.htmlFor=el.id;}else if(el.placeholder)el.setAttribute('aria-label',el.placeholder);});}
 let fieldNumber=0,busy=false;
 function enhance(){if(busy||!main)return;busy=true;try{main.dataset.uxView=VIEW;headers();health();sources(main);draft();criteria();approval();compactFilters();reportDepartments();quality();toolbar();navigation();orderPage();accessible(main);}finally{busy=false;}}
 function enhanceModal(){const root=document.getElementById('modal');if(!root)return;accessible(root);const headings=[...root.querySelectorAll('form h4')];if(headings.length>1&&!root.querySelector('.ux-form-guide')){const guide=document.createElement('nav');guide.className='ux-form-guide';guide.setAttribute('aria-label','ส่วนของแบบฟอร์ม');headings.forEach((h,i)=>{const button=document.createElement('button');button.type='button';button.innerHTML=`<b>${i+1}</b> ${esc(h.textContent.replace(/^\d+[.·\s-]*/,''))}`;button.onclick=()=>h.scrollIntoView({behavior:'smooth',block:'start'});guide.append(button);});root.querySelector('.modal-h')?.after(guide);}}
 for(const view of Object.keys(RENDER)){const original=RENDER[view];RENDER[view]=function(...args){const active=document.activeElement,keep=VIEW===view&&main.contains(active)&&active.tagName==='INPUT'&&['search','text'].includes(active.type)&&!!active.closest('.filterbar,.issue-work-filters,.activity-filters');const focus=keep?{id:active.id,placeholder:active.placeholder,value:active.value,start:active.selectionStart,end:active.selectionEnd}:null;const finish=()=>{enhance();if(focus&&VIEW===view){const input=focus.id?document.getElementById(focus.id):[...main.querySelectorAll('input')].find(n=>n.placeholder===focus.placeholder&&n.value===focus.value);if(input&&input.value===focus.value){input.focus({preventScroll:true});try{input.setSelectionRange(focus.start,focus.end);}catch{}}}};const result=original(...args);finish();if(result?.then)return result.then(value=>{if(VIEW===view)finish();return value;});return result;};}
 const originalModal=showModal;showModal=function(...args){const result=originalModal(...args);enhanceModal();return result;};
 let queued=false;const observer=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance();});});observer.observe(main,{childList:true,subtree:true});
 window.companyUxEnhance=enhance;window.companyUxEnhanceModal=enhanceModal;enhance();
})();
